[tools]
bun = "latest"
go = "latest"
node = ['22', '24', 'lts']
"npm:pnpm" = ['10', 'latest']
python = "3.13"
rust = "latest"
uv = "latest"
claude = "latest"
yarn = ['1','latest']
codex = "latest"
gemini-cli = "latest"
opencode = "latest"
act = "latest"
gomigrate = "latest"


"npm:serve" = "latest"
"npm:npm-check-updates" = "latest"
# "npm:@google/gemini-cli" = "latest"
# "npm:@qwen-code/qwen-code" = "latest"
"npm:claude-code-workflow" = "latest"
# "npm:@augmentcode/auggie" = "prerelease"
"npm:maestro-flow" = "latest"
"npm:typescript" = "latest"
"npm:@qoder-ai/qodercli" = "latest"
"npm:@qodercn-ai/qoderclicn" = "latest"
"npm:@moonshot-ai/kimi-code" = "latest"


"pipx:cccc-pair" = "latest"

"aqua:rhysd/actionlint" = "latest"
"aqua:air-verse/air" = "latest"

[tasks.claude]
run = "mise exec node@lts -- claude"

[settings]
idiomatic_version_file_enable_tools = []
