[tools]
bun = "latest"
go = "latest"
node = ['22','24','25','lts']
"npm:pnpm" = ['11','10']
python = "3.13"
rust = "latest"
uv = "latest"
claude = "latest"
yarn = ['1','latest']
codex = "latest"
gemini-cli = "latest"
php = "latest"


"npm:serve" = "latest"
"npm:npm-check-updates" = "latest"
# "npm:@google/gemini-cli" = "latest"
# "npm:@qwen-code/qwen-code" = "latest"
"npm:claude-code-workflow" = "latest"
# "npm:@augmentcode/auggie" = "prerelease"
"npm:maestro-flow" = "latest"
"npm:typescript" = "latest"

"pipx:cccc-pair" = "latest"
# "pipx:kimi-cli" = "latest"
# "pipx:kimi-cli" = { version = "latest", python = "3.13" }

"aqua:rhysd/actionlint" = "latest"
"aqua:air-verse/air" = "latest"

[tasks.claude]
run = "mise exec node@lts -- claude"

[tasks.install-kimi]
run = "uv tool install --python 3.13 kimi-cli"

[tasks.upgrade-kimi]
run = "uv tool upgrade kimi-cli --no-cache"

[settings]
idiomatic_version_file_enable_tools = []
